### ISSUE TITLE
About baseline methods

### ISSUE THREAD

**Issue by Chuan1997** [Jinjiarui/GraphHINGE#4]
您好，请问能否提供您选用的一些baseline方法的代码呢，因为我发现许多的源码具有特异性，而我刚入门这个领域，对于如何改写这些模型感到困惑
（例如LGRec和MCRec它们的initial embedding的详细生成方法并未提供，而且LGRec的模型代码似乎跑不通；HetGNN模型是hard coded for academic paper，怎么改用到其他数据呢？HAN模型是embedding方法，如果要改用到推荐，该如何实现呢？）
希望能得到您的回复

**Comment by Jinjiarui** [comment]
For baselines, the initial embeddings for nodes are often randomized unless otherwise stated. One solution is to employ their methods following the description of the algorithm in their papers. Their implementations may be limited within certain datasets but their algorithms are kind of general idea for the heterogeneous graphs.  GNN methods are mainly used as encoding methods. That is to say, after obtaining the node embedding, it's straightforward to compute the similarity between the source and target nodes to derive the prediction score for the link existance.
